### PR TITLE
Added additional badges to README.rst

### PR DESCRIPTION
**Pull request by gregseb**
- Requires.io badge to show that our requirements are up to date
- badge.fury.io to show our latest pypi release

### CODE REVIEW

**Comment by gregseb** [comment]
This was originally a pull request specifically for the require.io and badge.fury.io badges, but I decided to try some additional badges and see how they look here.

**Comment by gregseb** [comment]
Good collection of shields here: https://shields.io/

**Comment by gregseb** [comment]
I wonder if its bad form to have two rows of badges?  I don't want to go too badge crazy, but I kind of like having build badges and release badges separated.

**Comment by spatialbits** [comment]
Sure that looks ok. These are helpful badges. I agree we don't want too much clutter and this is probably enough badginess for now.

**Pull request merged**
