### PR TITLE
New/tests

### PR DESCRIPTION
**Pull request by gregseb**
Creating a pull request as a location to discuss the test structure so far.

I had intended to use the pytest-dependency package to make it so that further tests will be skipped if test_create fails.  However as mentioned in the commit message of https://github.com/pauperpythonistas/python-geomark/commit/a1e1e70f68125fec0e94204490d460f350c39d59 pytest-dependency currently has an issue where attempts to install with pipenv fail due to an attempt to import its own module in setup.py.  This will be fixed in their 0.3 release.  Until I don't believe any harm is done by leaving references to @pytest.mark.dependency for now.

I intend to shortly replace the current geojson files located in ./tests/files/ with the roughly formatted geojson currently being used for expected values.  The geojson there is the same geojson that is returned by calling Geomark.feature() with a little trimming done to remove/repair variable properties.

Currently only test_point, test_copy, and test_copy_multiple are remaining.  I'm not 100% certain how best to tackle deriving the expected geometries for test_point due to the strange way that [geomark appears to derive this value themselves](ca.bc.gov.geomark.web.rest.Geomark.getGeomarkPoint).  

I'm wondering if the easiest thing to do would be to simply store a separate geojson file with the expected return values for .point()  And in that case, why not do the same for all the tests?  I think this is my vote.  This is a good time to convert the storage for all expected values to be a directory of files.  The files stored will need a little cleaning done to remove variable values.  This will be documented somewhere.. in a comment likely.  This will also simplify the process for test_copy and test_copy_multiple

### CODE REVIEW

**Comment by spatialbits** [comment]
@gregseb since we're including the `shapely` module for testing, I think the tests could be made a bit easier `shapely`'s `.equals` method. It would be a more "spatial" test rather than a dict to dict comparison as it would be comparing geometries. You would also then be able to ditch the `strip_variable_properties` method.

**Comment by gregseb** [comment]
I removed shapely actually, and cleaned up all the tests to use a json file with the results of the tested function that I pulled manually.
currently the test_copy_multiple fails.  I'm out of time to look into it at this moment though.  For some reason it seems to result in two sets of features... It copies the three single geometry Geomarks, but results in 6 geometries.

**Comment by gregseb** [comment]
After test_copy_multiple is finished assuming your happy with the current structure, I think we can merge this.

**Comment by spatialbits** [comment]
Well look at that, the Geomark service is currently throwing `503`s:
https://github.com/bcgov/dbcrss/blob/master/heartbeat/data/geomark-heartbeat.txt

**Comment by spatialbits** [comment]
ok so the problem looks like the order of the three geometry components is getting altered when the `json.loads` and `strip_variable_properties` are performed. 

There is also a teeny tiny shift in the `centroidX` coordinate. I can't explain that. 

I really think we should reconsider putting `shapely` back in and drop the `strip_variable_properties` method. `shapely` gives us super quick way to rigorously compare geometries and ignore non-spatial attributes coming back in the response. 

The shapely docs say an overlapping multi-part polygon geometry should be "invalid" - which is consistent with our results; that would be a good test.

Then decompose the multi-polygon into it's three parts and testing for 1. validity (all are true) and 2. equality (all are equal as well).

I'll make a commit on this PR to show what I mean.

**Comment by spatialbits** [comment]
that's odd - Travis didn't use the committed changes in the test run.

**Comment by gregseb** [comment]
So after talking with adam for awhile, it would appear that there were issues with the Geomark Service over the weekend that was causing my double geometries issue which was no longer the issue after the service came back online.  However it was clear that there were some issues with some of the Geomark calculated stats being different after the service coming back online, and the order that I was passing the GeomarkIds to copy.    

Adam has suggested we bring back shapely, and use some of its tools to assist with comparing geometries to help combat the fact that we are testing against a bit of a moving target.

He also is in favour of stripping out properties and not caring about them compared to Geometries.   I suggest we further discuss that at another time in a different issue/pr.

**Comment by spatialbits** [comment]
Thanks for the summary Greg. I'd only say that I _am_ in favour of testing returned properties and agree we could postpone for now.

**Pull request merged**
